/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RunEvent = StartEvent | DeltaEvent | ToolEvent | StepEvent | DoneEvent | ErrorEvent;
export type StartEvent = EventBase & {
  type: "start";
  metadata: {
    [k: string]: unknown;
  } | null;
  profile: string;
  harness: string;
  model: string;
  [k: string]: unknown;
};
export type DeltaEvent = EventBase & {
  type: "delta";
  kind: "content" | "reasoning";
  text: string;
  [k: string]: unknown;
};
export type ToolEvent = EventBase & {
  type: "tool";
  id: string;
  name: string;
  arguments: unknown;
  output: string;
  is_error: boolean;
  [k: string]: unknown;
};
export type StepEvent = EventBase & {
  type: "step";
  step: number;
  usage: Usage;
  cost: number;
  metrics?: StepMetrics | null;
  [k: string]: unknown;
};
export type DoneEvent = EventBase & {
  type: "done";
  answer: string;
  stop_reason: string;
  steps: number;
  usage: Usage;
  cost: number;
  metrics?: RunMetrics | null;
  error: string | null;
  profile: string;
  harness: string;
  model: string;
  [k: string]: unknown;
};
export type ErrorEvent = EventBase & {
  type: "error";
  code: string;
  error: string;
  [k: string]: unknown;
};

export interface EventBase {
  runId: string;
  [k: string]: unknown;
}
export interface Usage {
  [k: string]: number;
}
export interface StepMetrics {
  step: number;
  duration_s: number;
  model_s: number;
  tools_s: number;
  overhead_s: number;
  usage: Usage;
  cost: number;
  model_calls: ModelCallMetrics[];
  tool_calls: ToolCallMetrics[];
  [k: string]: unknown;
}
export interface ModelCallMetrics {
  kind: string;
  duration_s: number;
  ttft_s: number | null;
  generation_s: number | null;
  output_tokens_per_second: number | null;
  usage: Usage;
  cost: number;
  error: string | null;
  [k: string]: unknown;
}
export interface ToolCallMetrics {
  id: string;
  name: string;
  duration_s: number;
  is_error: boolean;
  error: string | null;
  [k: string]: unknown;
}
export interface RunMetrics {
  duration_s: number;
  model_s: number;
  tools_s: number;
  overhead_s: number;
  usage: Usage;
  cost: number;
  steps: StepMetrics[];
  [k: string]: unknown;
}
