/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Message = {
  [k: string]: unknown;
} & {
  role: "user" | "assistant" | "tool";
  content: string;
  tool_call_id?: string;
};

export interface RunRequest {
  input: string;
  instructions?: string;
  /**
   * @maxItems 200
   */
  messages?: Message[];
  metadata?: {
    [k: string]: unknown;
  };
}
